name: quiz_engine_core
description: "Quiz engine core"
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  uuid: ^4.5.1
  shared_services:
    path: ../shared_services

dev_dependencies:
  test: ^1.21.6
  mockito: ^5.3.1
  build_runner:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  lints: ^3.0.0
  coverage: ^1.6.0
  fake_async: ^1.3.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:


